> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# 5 Miscellaneous Functions in Numpy


Write a short introduction about Numpy and list the chosen functions. 

- np.insert() 
- intersect1d()
- reshape()
- Matrix Multiplication (matmul(), @)
- setdiff1d()

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [17]:
!pip install jovian --upgrade -q

In [18]:
import jovian

In [19]:
import numpy as np

In [20]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
API KEY: ········
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [2]:
import numpy as np

In [21]:
# List of functions explained 
function1 = np.insert
function2 = np.intersect1d
function3 = np.reshape
function4 = np.matmul
function5 = np.setdiff1d


## Function 1 - np.insert()

'np.insert()' is a function which is used to insert value into an array. 

In [22]:
import numpy as np

In [23]:
# Example 1 - working 

arr1 = np.array([1,2,3,5,6])
np.insert(arr1, 3, 4)

array([1, 2, 3, 4, 5, 6])

Explanation about example : arr1 is the array in which we want to insert element, 3 is the index position and 4 is the number to be inserted. 

In [25]:
# Example 2 - working

arr2 = np.array([[1,2,3],[5,6,7],[8,9,10]])
np.insert(arr2,3, 4, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  4],
       [ 8,  9, 10,  4]])

Explanation about example : arr2 is a two dimensional array. axis=1 depicts to add number 4 at the 3 rd column of arr2

In [26]:
# Example 3 - working

arr3 = np.array([[1,2,3],[7,8,9]])
np.insert(arr3, 4, 5, axis=0)

IndexError: index 4 is out of bounds for axis 0 with size 2

Explanation about example : The above example breaks because the index mentioned is out of bounds.

We use this function to add a column or a row to an array.

In [27]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

## Function 2 - intersect1d()

intersect1d() function in numpy is performed on two arrays or two lists. The result is the elements that are common in both arrays or lists.

In [28]:
import math
import numpy as np

In [29]:
# Example 1 - working

n1 = np.array([10,20,30,40,50])
n2 = np.array([40,50,60,70,80])
np.intersect1d(n1,n2)

array([40, 50])

Explanation about example : The intersect function is used to print the common elements from the two arrays, lists.

In [30]:
# Example 2 - working

a1 = np.array([[10,20,30],[40,50,60]])
b1 = np.array([[40,50,60],[30,50,20]])
np.intersect1d(a1,b1)


array([20, 30, 40, 50, 60])

Explanation about example : The output array is the collection of values which are common in both a1 and b1

In [32]:
# Example 3 - working

q1 = np.array([1,2,3])
q2 = np.array([3,4,5])
q3 = np.array([3,5,6])
np.intersect1d(q1,q2,q3)



#  Solution is 
# result1 = np.intersect1d(q1,q2)
# np.intersect1d(result1,q3)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

Explanation about example : To perform the intersection operation between three arrays we first perfrom intersection1d() on first two arrays and store in another array and then perform with the third array.

The intersect1d() function can be used to find the common elements of arrays.

In [33]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

## Function 3 - reshape()

reshape function is basically used to shape an array without changing the data of an array.

In [34]:
# Example 1 - working
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

A list can be converted into a reshaped array using reshape function and the condititon is 
Total number of elements = (number of rows) * (number of columns)


In [35]:
# Example 2 - working
tuple1 = (1,2,3,4,5,6)
arr2 = np.array(tuple1).reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

tuple can also be converted into a reshaped array using reshape function and the condition is 
Total number of elements in tuple = (number of rows) * (number of columns)

In [36]:
# Example 3 - breaking (to illustrate when it breaks)
list3 = [1,2,3,4,5,6]
arr3 = np.array(list3).reshape(2,4)
arr3

ValueError: cannot reshape array of size 6 into shape (2,4)

In this example the list has 6 elements and reshape arguments are 2 and 4 so the condition is 
6 != (2*4) which means 6 elements can't be reshaped into 2*4 matrix

reshape() function is used to create a matrix based on the number of elements.

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

## Function 4 - Matrix Multiplication

Matrix multiplication can also be done easily using numpy library.

In [38]:
# Example 1 - working
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
np.matmul(arr1,arr2)

array([14, 32])

Matrix multiplication of arr1 and arr2 can be done using np.matmul function.

In [39]:
# Example 2 - working
arr1 = np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2,3])
arr1 @ arr2

array([14, 32])

Instead of using np.matmul we can also use '@' between two arrays to multiply them.


In [40]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1,2,3],[4,5,6]])
arr2=np.array([1,2])
arr1 @ arr2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

This code doesn't get executed because to perform matrix multiplication the number of columns of first array must be equal to the number of rows of second array.

np.matmul and '@' can be used to perform matrix multiplication operations.

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

## Function 5 - setdiff1d()


This function compares two arrays and prints the elements which are present only in first array but not in sencond array

In [42]:
import numpy as np

In [43]:
# Example 1 - working
n1 = np.array([10,20,30,40,50])
n2 = np.array([30,60,80,90,70])
np.setdiff1d(n1,n2)


array([10, 20, 40, 50])

the elements present only in n1 are printed. The elements that are mutual are not printed.

In [44]:
# Example 2 - working
n1 = np.array([10,20,30,60])
n2 = np.array([10,40,50])
n3 = np.array([40,50,70])

n4 = np.setdiff1d(n1,n2)

np.setdiff1d(n4,n3)

array([20, 30, 60])

Result is an empty list since n1 contains only 1 elements and it is mutual.

In [45]:
# Example 3 - breaking (to illustrate when it breaks)
n1 = np.array([10,20,30])
n2 = np.array([20,30,40])
n3 = np.array([30,40,50])
np.setdiff1d(n1,n2,n3)



ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

np.setdiff1d() takes only two arguments of arrays. To perform setdiff1d() on three arrays we need to store the setdiff1d() of first two arrays and then perform setdiff1d() with the resultant array and third array .

Some closing comments about when to use this function.

In [46]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'

## Conclusion
 
This note book consists of 5 Miscellaneous functions in numpy.

## Reference Links

Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...https://numpy.org/doc/stable/reference/routines.html

In [84]:
import jovian


In [85]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "ajayannamaneni20/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/ajayannamaneni20/numpy-array-operations


'https://jovian.ml/ajayannamaneni20/numpy-array-operations'